db:
  host: MOVIECAT_DATABASE_HOST
  port: MOVIECAT_DATABASE_PORT
  user: MOVIECAT_DATABASE_USER
  password: MOVIECAT_DATABASE_PASSWORD
  database: moviecat

server:
  route: /v1/moviecat
  port: 6636